[package]
name = "browser-structure"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]
path = "engine.rs"

[dependencies]
legal-structure = { git = "https://github.com/eliziff/legal-structure-parser.git", rev = "f73bcd5d66575c0504e97fc2c3b95bf5589377e5", features = ["provider-text"] }
serde_json = "1"

[profile.release]
opt-level = "s"
lto = true
strip = true
